[package]
name = "nova-dashboard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nova-dashboard"
path = "src/main.rs"

[dependencies]
sdl2        = "0.37"
tiny-skia   = "0.11"
serde_json  = "1"
zbus        = { version = "4", features = ["tokio"] }
tokio       = { version = "1", features = ["rt", "rt-multi-thread", "time", "macros"] }
serde       = { version = "1", features = ["derive"] }
fontdue     = "0.9"
parking_lot = "0.12"
image       = { version = "0.25", default-features = false, features = ["png"] }
log         = "0.4"
env_logger  = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
socketcan   = "3"
